config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home/search' => 'home#search'
  get 'home/wordsearch' => 'home#wordsearch'
  get 'home/blank' => 'home#blank'
  get 'home/indexbookmark' => 'home#indexbookmark'
  get 'home/indexcomment' => 'home#indexcomment'
  get 'home/taglist' => 'home#taglist'
  get 'home/regulation' => 'home#regulation'
  get 'home/contact' => 'home#contact'
  get 'home/about' => 'home#about'

  #userのブックマーク一覧へのリンク
  resources :users, only: [:bookmark,:comment] do
    get :bookmark
    get :comment
  end

  resources :users, only: [:show]
  resources :home, only: [:index,:show]
  resources :comment, only: [:destroy]

  #ブックマーク機能用。paramsを渡すため・・
  resources :home, only: [:bookmark,:unbookmark] do
    post :bookmark
    delete :unbookmark
  end

  resources :home do
    resources :comment, only: [:create]
  end



  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :news
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :user_name, presence: true
  validates :news_id, presence: true
  validates :user_id, presence: true
  validates :comment, presence: true, length: {maximum: 1000}
  belongs_to :news
  belongs_to :user

  #コメントしているかどうかの判定
  def commented?(id)
    user_id == id
  end

end

app/models/news.rb
class News < ApplicationRecord
  validates :name,:text,:tag,:link,:bookmark,:quotation,:comment,  presence: true
  has_many :comments
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks

  #アソシエーションにより使えるようになるメソッド
  def bookmarkcheck(news_id,user_id)
    bookmarks.exists?(news_id: news_id, user_id: user_id)
  end


end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name,:type, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :news, through: :bookmarks
  validates :introduction, length: {maximum: 500}

  #carrierwave用
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:image,:job,:introduction])
      devise_parameter_sanitizer.permit(:account_update, keys: [:nickname,:image,:job,:introduction])
    end


end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

  before_action :move_to_root


  def create
    @newcomment = Comment.new(commentparams)

    respond_to do |format|

      if @newcomment.save

        news = News.find(params[:home_id])
        pluscount = news.comment + 1
        news.update(comment: pluscount)

        @comments = Comment.where(news_id: params[:home_id]).order(created_at: :desc)
        @news = News.find(params[:home_id])

        format.html {redirect_to "/home/#{params[:home_id]}"}
        format.js

      else

        @news = News.find(params[:home_id])
        @comments = Comment.where(news_id: params[:home_id]).order(created_at: :desc)

        format.html {render "home/show"}
        format.js

      end

    end

  end


  #コメントの削除
  def destroy
    comment = Comment.find(params[:id])
    minuscount = comment.news.comment - 1
    id = comment.news.id

    comment.news.update(comment: minuscount)
    comment.destroy

    @comments = Comment.where(news_id: id).order(created_at: :desc)
    @news = News.find(id)

    respond_to do |format|

      format.html {redirect_to "/home/#{id}"}
      format.js

    end

  end


private

#require(:xxx)とつけることで、[:xxx][:text]..のような形のハッシュを受けられる

  def commentparams
    params.require(:comment).permit(:comment).merge(user_name: current_user.nickname, news_id: params[:home_id], user_id: current_user.id)
  end

  def move_to_root
    redirect_to root_path  unless user_signed_in?
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :move_to_root, only: [:bookmark, :unbookmark]

  def index
    @allnews = News.all.order(created_at: :desc).page(params[:page]).per(20)
  end

  def indexbookmark
    @allnews = News.all.order(bookmark: :desc).page(params[:page]).per(20)
  end

  def indexcomment
    @allnews = News.all.order(comment: :desc).page(params[:page]).per(20)
  end


  def taglist
    @tag1lists = Tag.where(sort: "電池").order(hiragana: :asc)
    @tag2lists = Tag.where(sort: "半導体").order(hiragana: :asc)
    @tag3lists = Tag.where(sort: "自動運転").order(hiragana: :asc)
    @tag4lists = Tag.where(sort: "AI・人工知能").order(hiragana: :asc)
    @tag5lists = Tag.where(sort: "企業").order(hiragana: :asc)
  end



  def show
    @newcomment = Comment.new
    @news = News.find(params[:id])
    @comments = Comment.where(news_id: params[:id]).order(created_at: :desc)
  end

  def search
    @results = News.where('tag LIKE(?)', "%#{params[:searchword]}%")
  end

  def wordsearch
    if params[:wordsearch].empty?
      redirect_to home_blank_path
    else
      @results = News.where('name LIKE(?)', "%#{params[:wordsearch]}%")
    end
  end

  def bookmark
    Bookmark.create(user_id: current_user.id, news_id: params[:home_id])
    news = News.find(params[:home_id])
    pluscount = news.bookmark + 1
    news.update(bookmark: pluscount)

    @news = News.find(params[:home_id])

    respond_to do |format|

      format.html {redirect_to "/home/#{params[:home_id]}"}
      format.js

    end
  end

  def unbookmark
    bookmark = Bookmark.find_by(user_id: current_user.id, news_id: params[:home_id])
    bookmark.destroy
    news = News.find(params[:home_id])
    minuscount = news.bookmark - 1
    news.update(bookmark: minuscount)

    @news = News.find(params[:home_id])

    respond_to do |format|

      format.html {redirect_to "/home/#{params[:home_id]}"}
      format.js

    end
  end


  private

  def move_to_root
    redirect_to root_path unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :move_to_root, only: [:bookmark,:comment]

  def show
    @user = User.find(params[:id])
  end

  def bookmark
    @bookmarks = current_user.news.order(created_at: :desc)
  end

  def comment
    comments = Comment.where(user_id: current_user.id)

    @commentednews = []

    comments.each do |comment|
      @commentednews << News.find(comment.news_id)
    end

    #ユーザーがコメントしたニューズ一覧から、重複を削除
    @commentednews.uniq!

    #created_atの降順で並び替え。モデルの後ろに直接書くorderメソッドは使えない。
    @commentednews.sort! do |a,b|
      b[:created_at] <=> a[:created_at]
    end


  end



  private

  def move_to_root
    redirect_to root_path unless user_signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  #アプリケーション全体に渡って使うヘルパーメソッドを定義

#deviseのエラーメッセージのカスタマイズ。GitHubから拾ってきたもの。
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages
    return "" if resource.errors.empty?

#rubyのmapメソッド,joinメソッドとrailsのcontent_tagメソッドが使用されている
    messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg) }.join
#   sentence = I18n.t("errors.messages.not_saved",
#                      count: resource.errors.count,
#                      resource: resource.class.model_name.human.downcase)

    #以下はヒアドキュメントになってる
    html = <<-HTML
    <div class="errormessage">
      #{messages}
    </div>
    HTML

    html.html_safe
  end

  #news.pictureがnilかどうか
  def picturenil?(instance)
    instance.picture.nil?
  end

end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_arrangement.html.erb
<div class="arrange-wrapper">


  <div class="arrange_icon">
    <%= link_to home_index_path, style: "text-decoration: none;" do %>
      <i class="far fa-calendar-alt fa-3x"></i>
    <% end %>

    <p class="arrange_text">新しい投稿から並べる</p>
  </div>


  <div class="arrange_icon" id="icon2">
    <%= link_to home_indexbookmark_path, style: "text-decoration: none;" do %>
     <i class="far fa-bookmark fa-3x"></i>
    <% end %>

    <p class="arrange_text">ブックマークの多い順に並べる</p>
  </div>


  <div class="arrange_icon" id="icon3">
    <%= link_to home_indexcomment_path, style: "text-decoration: none;" do %>
      <i class="far fa-comments fa-3x"></i>
    <% end %>

    <p class="arrange_text">コメントの多い順に並べる</p>
  </div>


  <div class="arrange_icon" id="icon4">
    <%= link_to home_taglist_path, style: "text-decoration: none;" do %>
      <i class="fas fa-tags fa-3x"></i>
    <% end %>

    <p class="arrange_text">タグで調べる</p>
  </div>


</div>

app/views/application/_arrangement2.html.erb
<div class="arrange-wrapper">


  <div class="arrange_icon2">
    <%= link_to edit_user_registration_path, style: "text-decoration: none;" do %>
      <i class="fas fa-edit fa-3x"></i>
    <% end %>

    <p class="arrange_text">ユーザー情報の編集</p>
  </div>


  <div class="arrange_icon2" id="icon2">
    <%= link_to user_bookmark_path(current_user), style: "text-decoration: none;" do %>
     <i class="far fa-bookmark fa-3x"></i>
    <% end %>

    <p class="arrange_text">ブックマークした記事一覧</p>
  </div>


  <div class="arrange_icon2" id="icon3">
    <%= link_to user_comment_path(current_user), style: "text-decoration: none;" do %>
      <i class="far fa-comments fa-3x"></i>
    <% end %>

    <p class="arrange_text">コメントした記事一覧</p>
  </div>


</div>

app/views/application/_commentsize.html.erb
<i class="far fa-comments"></i>&ensp;<%= var.comments.size %>

app/views/application/_errormsg.html.erb
<% if var.errors.any? %>

  <div class="errormessage">
    <% var.errors.full_messages.each do |message| %>
    <p><i class="far fa-times-circle"></i>&ensp;<%= message.delete("・") %></p>
    <% end %>
  </div>

<% end %>

app/views/application/_index.html.erb
 <% variables.each do |variable| %>

  <div class="index">

   <div class="title">
     <%= link_to "#{variable.name}", home_path(id: variable.id), style: "text-decoration: none;" %>
    </div>

   <div>
    <%= render 'taglist', var: variable %>
   </div>


   <div class="news-wrapper">

    <% if picturenil?(variable) %>

      <div class="picture-wrapper">
        <%= image_tag('noimage.jpg',width: "80%", height: "150px", class: "imagestyle") %>
      </div>

      <div class="comment-wrapper">
        <%= simple_format(variable.text) %>
      </div>

    <% else %>

      <div class="picture-wrapper">
        <%= image_tag(variable.picture,width: "80%", height: "150px", class: "imagestyle") %>
      </div>

      <div class="comment-wrapper">
        <%= simple_format(variable.text) %>
      </div>

    <% end %>
   </div>


   <div class="bookmark-wrapper">
     <span class="bookmark"><i class="far fa-bookmark"></i>&ensp;<%= variable.bookmarks.size %></span>&emsp;
     <span class="comments"><i class="far fa-comments"></i>&ensp;<%= variable.comments.size %></span>&emsp;
     <%= time_ago_in_words(variable.created_at) %>前&emsp;
     <i style="color: gray;"><%= variable.quotation %></i>
   </div>

  </div>

<% end %>

app/views/application/_taglist.html.erb
<% tags = var.tag.split(/、/) %>
<% tags.each do |tag| %>
  <span class="tag">
    <i class="fas fa-tags"></i>
    <%= link_to "#{tag}", home_search_path(searchword: "#{tag}"), style: "text-decoration: none; color: white;" %>
  </span>
<% end %>

app/views/comment/create.js.erb
$("#textfield").val("");
$("#errors").html("<%= j(render 'errormsg', var: @newcomment) %>");
$("#ajaxcomment").html("<%= j(render @comments) %>");
$("#commentsize").html("<%= j(render 'commentsize', var: @news) %>");

app/views/comment/destroy.js.erb
$("#commentsize").html("<%= j(render 'commentsize', var: @news) %>");
$("#ajaxcomment").html("<%= j(render @comments) %>");

app/views/comments/_comment.html.erb
    <div class="user_comment_wrapper">

      <div class="image_name_wrapper">
        <%= link_to user_path(comment.user), style: "text-decoration: none;" do %>
        <div>
         <% if comment.user.image.blank? %>
           <%= image_tag('noimage.jpg', style: "width:50px; height:50px; border-radius: 25px;") %>
         <% else %>
           <%= image_tag(comment.user.image, style: "width:50px; height:50px; border-radius: 25px;") %>
         <% end %>
        </div>
        <% end %>

        <div class="name_wrapper">
          <%= comment.user_name %>&emsp;<span style="color: gray;"><%= time_ago_in_words(comment.created_at) %>前</span><br>
          <span style="color: gray;"><%= comment.user.job %></span>
        </div>
      </div>  <%# /.image_name_wrapper %>


      <div>
      <%= simple_format(comment.comment) %>
        <% if comment.commented?(current_user.id) %>
          <%= link_to "コメントを削除", comment_path(comment), method: :delete, data: {confirm: "コメントを削除しますか？"},
          style: "text-decoration: none;", remote: true %>
        <% end %>
      </div>
    </div> <%# /.user_comment_wrapper %>

app/views/home/_bookmarkcheck.html.erb
<% if var.bookmarkcheck(var.id, current_user.id) %>

  <%= link_to "ブックマーク中", home_unbookmark_path(var), method: :delete, class: "unbookmark_btn", remote: true %>

<% else %>

  <%= link_to "ブックマークする", home_bookmark_path(var), method: :post, class: "bookmark_btn", remote: true %>

<% end %>

app/views/home/_bookmarksize.html.erb
<i class="far fa-bookmark"></i>&ensp;<%= var.bookmarks.size %>

app/views/home/_logoutcomments.html.erb
    <div class="user_comment_wrapper">


      <div class="image_name_wrapper">
        <%= link_to user_path(comment.user), style: "text-decoration: none;" do %>
        <div>
         <% if comment.user.image.blank? %>
           <%= image_tag('noimage.jpg', style: "width:50px; height:50px; border-radius: 25px;") %>
         <% else %>
           <%= image_tag(comment.user.image, style: "width:50px; height:50px; border-radius: 25px;") %>
         <% end %>
        </div>
        <% end %>

        <div class="name_wrapper">
          <%= comment.user_name %>&emsp;<span style="color: gray;"><%= time_ago_in_words(comment.created_at) %>前</span><br>
          <span style="color: gray;"><%= comment.user.job %></span>
        </div>
      </div>  <%# /.image_name_wrapper %>


      <div>
      <%= simple_format(comment.comment) %>
      </div>
    </div> <%# /.user_comment_wrapper %>

app/views/home/_tagtemplete.html.erb
<div class="tag-wrapper">
  <% taglists.each do |taglist| %>
    <span class="tag">
     <i class="fas fa-tags"></i>
        <%= link_to "#{taglist.name}(#{News.where('tag LIKE?', "%#{taglist.name}%").count})", 
        home_search_path(searchword: "#{taglist.name}"), 
       style: "text-decoration:none; color: white;" %>
     </span>
  <% end %>
</div>

app/views/home/about.html.erb
<h2 style="text-align: center;">Techcollect.について</h2>

<p style="text-align: center;">
Techcollect.は、科学技術・テクノロジーに関するニュースや有益な情報を収集します。<br>
ユーザーの皆様は会員登録を行うことで、ニュースへのコメントやブックマークが行えます。<br>
普段の仕事に、知的好奇心の探求に、是非お役立てください。
</p>

app/views/home/bookmark.js.erb
$("#bookmarksize").html("<%= j(render 'bookmarksize', var: @news) %>");
$("#bookmarkcheck").html("<%= j(render 'bookmarkcheck', var: @news) %>");

app/views/home/index.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= render 'arrangement' %>


<%= render 'index', variables: @allnews %>

<div style="text-align: center; margin-top: 3%;">
<%= paginate(@allnews) %>
</div>

app/views/home/indexbookmark.html.erb
<%= render 'arrangement' %>

<%= render 'index', variables: @allnews %>

<div style="text-align: center; margin-top: 3%;">
<%= paginate(@allnews) %>
</div>

app/views/home/indexcomment.html.erb
<%= render 'arrangement' %>

<%= render 'index', variables: @allnews %>

<div style="text-align: center; margin-top: 3%;">
<%= paginate(@allnews) %>
</div>

app/views/home/search.html.erb
<div class="search-wrapper">
  「<%= params[:searchword] %>」を含むニュース（全<%= @results.count %>件)
</div>


<%= render 'index', variables: @results %>

app/views/home/show.html.erb
<div class="show-wrapper">

  <div class="title">
    <%= link_to "#{@news.name}", "#{@news.link}", target: "_new", style: "text-decoration: none;" %>
  </div>

  <div>
    <%= render 'taglist', var: @news %>
  </div>


   <div class="news-wrapper">

    <% if picturenil?(@news) %>

      <div class="picture-wrapper">
        <%= image_tag('noimage.jpg',width: "80%", height: "150px", class: "imagestyle") %>
      </div>

      <div class="comment-wrapper">
        <%= simple_format(@news.text) %>
      </div>

    <% else %>

      <div class="picture-wrapper">
        <%= image_tag(@news.picture,width: "80%", height: "150px", class: "imagestyle") %>
      </div>

      <div class="comment-wrapper">
        <%= simple_format(@news.text) %>
      </div>

    <% end %>
   </div>



   <div class="bookmark-wrapper">
     <span class="bookmark" id="bookmarksize"><%= render 'bookmarksize', var: @news %></span>&emsp;
     <span class="comments" id="commentsize"><%= render 'commentsize', var: @news %></span>&emsp;
     <%= time_ago_in_words(@news.created_at) %>前&emsp;
     <i style="color: gray;"><%= @news.quotation %></i>
   </div>


  <% if user_signed_in? %>

   <div id="bookmarkcheck">
    <%= render 'bookmarkcheck', var: @news %>
   </div>

  <% end %>


</div>  <%# end of .index %>



<% if user_signed_in? %>


  <%= form_for([@news,@newcomment], url: home_comment_index_path(@news), html: {method: :post}, remote: true ) do |f| %>

    <div id="errors">
      <%= render 'errormsg', var: @newcomment %>
    </div>

    <div style="text-align: center; margin-top: 50px;">
      <%= f.text_area :comment, maxlength: 1000, id: "textfield", class: "commentbox" %>
    </div>

    <br>

    <div style="text-align: center;">
    <%= f.submit "コメントする", data: {confirm: "この内容でコメントしますか？"}, class: "comment_btn" %>
    </div>

  <% end %>


  <div id="ajaxcomment">
    <% if @comments.empty? %>
      <div class="nocomment">コメントはありません。</div>
    <% else %>
      <%= render @comments %>
    <% end %>
  </div>


<% else %>


  <% if @comments.empty? %>

    <div class="nocomment">コメントはありません。</div>

  <% else %>

    <% @comments.each do |comment| %>
      <%= render 'logoutcomments', comment: comment %>
    <% end %>

  <% end %>


<% end %>

app/views/home/taglist.html.erb
<%= render 'arrangement' %>



<h1>電池</h1>


<%= render 'tagtemplete', taglists: @tag1lists %>


<br>

<h1>半導体</h1>


<%= render 'tagtemplete', taglists: @tag2lists %>


<br>

<h1>自動運転</h1>


<%= render 'tagtemplete', taglists: @tag3lists %>


<br>

<h1>AI・人工知能</h1>


<%= render 'tagtemplete', taglists: @tag4lists %>


<br>

<h1>企業</h1>


<%= render 'tagtemplete', taglists: @tag5lists %>

<br>
<br>

app/views/home/unbookmark.js.erb
$("#bookmarksize").html("<%= j(render 'bookmarksize', var: @news) %>");
$("#bookmarkcheck").html("<%= j(render 'bookmarkcheck', var: @news) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Techcollect.</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# font-awesome %>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  </head>

  <body link="#0033cc" vlink="#0033cc">

    <div class="all-wrapper">

      <header>
        <%= link_to "Techcollect.", root_path, class: "logo" %>

        <% if user_signed_in? %>

          <%= link_to "マイページ", user_path(current_user), class: :square_btn %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :square_btn %>

        <% else %>

          <%= link_to "新規登録", new_user_registration_path, class: :square_btn %>
          <%= link_to "ログイン", new_user_session_path, class: :square_btn %>

        <% end %>


        <%= form_tag(home_wordsearch_path, method: :get, id: :searchform) do %>
          <%= text_field_tag :wordsearch, '', placeholder: "ニュースを検索", id: :searchtextfield %>
          <%= button_tag type: :submit, id: :searchbutton do %>
            <i class="fas fa-search fa-2x"></i>
          <% end %>
        <% end %>




      </header>

      <div class="contents-wrapper">
        <%= yield %>
      </div>

      <footer>
        <div style="margin-top: 1.5%">
        <%= link_to "about Techcollect.", home_about_path, style:"text-decoration: none; cursor: pointer; color: white;" %>&emsp;&emsp;
        <%= link_to "利用規約", home_regulation_path, style:"text-decoration: none; cursor: pointer; color: white;" %>&emsp;&emsp;
        <%=link_to "お問い合わせ", home_contact_path, style:"text-decoration: none; cursor: pointer; color: white;" %>&emsp;&emsp;(c) 2018 Techcollect.
        </div>
      </footer>

    </div>

  </body>

</html>

app/views/users/bookmark.html.erb
<% if @bookmarks.empty? %>

  <div class="search-wrapper">
    ブックマークしたニュースはありません。
  </div>

<% else %>

  <div class="search-wrapper">
    ブックマークしたニュース（全<%= @bookmarks.count %>件）
  </div>

<% end %>


<%= render 'index', variables: @bookmarks %>

app/views/users/comment.html.erb
<% if @commentednews.empty? %>

  <div class="search-wrapper">
    コメントしたニュースはありません。
  </div>

<% else %>

  <div class="search-wrapper">
    コメントしたニュース（全<%= @commentednews.count %>件）
  </div>

<% end %>

<%= render 'index', variables: @commentednews %>